<a href="https://colab.research.google.com/github/himanshunarulaa/himanshu_3cs9/blob/main/ml_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:


# Question 1

# !pip install numpy
import numpy as np


# a)
arr = np.array([1, 2, 3, 6, 4, 5])
print(" reversed array",np.flip(arr))

# b)
array = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]] )
print(" Flatennig an array ", array.flatten() )

# c)
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])
# val = arr1 == arr2
# or
val = np.array_equal(arr1,arr2)
print( "comparing array ", val )


# d)
# i
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
most_freq_value_x = np.bincount(x).argmax()
indices_x = np.where(x == most_freq_value_x)
print("Most frequent value in x:", most_freq_value_x)
print("Indices of most frequent value in x:", indices_x)

# ii
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_freq_value_y = np.bincount(y).argmax()
indices_y = np.where(y == most_freq_value_y)
print("Most frequent value in y:", most_freq_value_y)
print("Indices of most frequent value in y:", indices_y)

# e)

gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i
sum_all_elements = gfg.sum()
print("Sum of all elements:", sum_all_elements)

# ii
sum_row_wise = gfg.sum(axis=1)
print("Sum of elements row-wise:", sum_row_wise)

# iii
sum_column_wise = gfg.sum(axis=0)
print("Sum of elements column-wise:", sum_column_wise)



# f)
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i
sum_diagonal_elements = np.trace(n_array)
print("Sum of diagonal elements:", sum_diagonal_elements)

# ii
eigen_values = np.linalg.eigvals(n_array)
print("Eigen values:", eigen_values)

# iii
eigen_vectors = np.linalg.eig(n_array)[1]
print("Eigen vectors:", eigen_vectors)

# iv
inverse_matrix = np.linalg.inv(n_array)
print("Inverse of matrix:", inverse_matrix)

# v
determinant = np.linalg.det(n_array)
print("Determinant of matrix:", determinant)


# g)

n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i
sum_diagonal_elements = np.trace(n_array)
print("Sum of diagonal elements:", sum_diagonal_elements)

# ii
eigen_values = np.linalg.eigvals(n_array)
print("Eigen values:", eigen_values)

# iii
eigen_vectors = np.linalg.eig(n_array)[1]
print("Eigen vectors:", eigen_vectors)

# iv
inverse_matrix = np.linalg.inv(n_array)
print("Inverse of matrix:", inverse_matrix)

# v
determinant = np.linalg.det(n_array)
print("Determinant of matrix:", determinant)


# h)
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product
inner_product = np.inner(x, y)
print("Inner product:", inner_product)

# Outer product
outer_product = np.outer(x, y)
print("Outer product:", outer_product)

# Cartesian product is not directly available in NumPy
def cartesian_product(arr1, arr2):
    return np.transpose([np.tile(arr1, len(arr2)), np.repeat(arr2, len(arr1))])

cartesian_product_result = cartesian_product(x.flatten(), y.flatten())
print("Cartesian product:", cartesian_product_result)








 reversed array [5 4 6 3 2 1]
 Flatennig an array  [1 2 3 2 4 5 1 2 3]
comparing array  True
Most frequent value in x: 1
Indices of most frequent value in x: (array([0, 5, 7, 8, 9]),)
Most frequent value in y: 1
Indices of most frequent value in y: (array([0, 1, 2]),)
Sum of all elements: 45
Sum of elements row-wise: [[14]
 [16]
 [15]]
Sum of elements column-wise: [[20  9 16]]
Sum of diagonal elements: 176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001
Sum of diagonal elements: 176
Eigen values: [98.16835147 28.097044   49.73460452]
Eigen vectors: [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse of matrix: [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant of matrix: 137180.0000000001
Inner product: [[17 52]
 [13 62]]
Outer product: [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian product: [[ 2  1]
 [ 3  1]
 [ 4  1]
 [ 3  1]
 [ 2  1]
 [ 9  1]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2  0]
 [ 3  0]
 [ 4  0]
 [ 3  0]
 [ 2  0]
 [ 9  0]
 [ 2  5]
 [ 3  5]
 [ 4  5]
 [ 3  5]
 [ 2  5]
 [ 9  5]
 [ 2 10]
 [ 3 10]
 [ 4 10]
 [ 3 10]
 [ 2 10]
 [ 9 10]
 [ 2  3]
 [ 3  3]
 [ 4  3]
 [ 3  3]
 [ 2  3]
 [ 9  3]]

# Question 2



array = np.array([[1, -2, 3], [-4, 5, -6]])

# i
abs_values = np.abs(array)
print("Element-wise absolute value:", abs_values)

# ii
flattened_array = array.flatten()
percentiles_flattened = np.percentile(flattened_array, [25, 50, 75])
percentiles_columns = np.percentile(array, [25, 50, 75], axis=0)
percentiles_rows = np.percentile(array, [25, 50, 75], axis=1)
print("Percentiles of flattened array:", percentiles_flattened)
print("Percentiles for each column:", percentiles_columns)
print("Percentiles for each row:", percentiles_rows)

# iii
mean_flattened = np.mean(flattened_array)
median_flattened = np.median(flattened_array)
std_flattened = np.std(flattened_array)
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)
print("Mean, Median, and Standard Deviation of flattened array:", mean_flattened, median_flattened, std_flattened)
print("Mean for each column:", mean_columns)
print("Median for each column:", median_columns)
print("Standard Deviation for each column:", std_columns)
print("Mean for each row:", mean_rows)
print("Median for each row:", median_rows)
print("Standard Deviation for each row:", std_rows)


# b)

a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)
print("Floor values:", floor_values)
print("Ceiling values:", ceiling_values)
print("Truncated values:", truncated_values)
print("Rounded values:", rounded_values)


Element-wise absolute value: [[1 2 3]
 [4 5 6]]
Percentiles of flattened array: [-3.5 -0.5  2.5]
Percentiles for each column: [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Percentiles for each row: [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]
Mean, Median, and Standard Deviation of flattened array: -0.5 -0.5 3.8622100754188224
Mean for each column: [-1.5  1.5 -1.5]
Median for each column: [-1.5  1.5 -1.5]
Standard Deviation for each column: [2.5 3.5 4.5]
Mean for each row: [ 0.66666667 -1.66666667]
Median for each row: [ 1. -4.]
Standard Deviation for each row: [2.05480467 4.78423336]
Floor values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded values: [-2. -2. -0.  0.  2.  2.  3.]

# Question 3


# a)
array = np.array([10, 52, 62, 16, 16, 54, 453])

# i
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)

# ii
indices_sorted_array = np.argsort(array)
print("Indices of sorted array:", indices_sorted_array)

# iii
smallest_elements = np.sort(array)[:4]
print("4 smallest elements:", smallest_elements)

# iv
largest_elements = np.sort(array)[-5:]
print("5 largest elements:", largest_elements)


# b)
array = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])

# i
integer_elements = array[array % 1 == 0]
print("Integer elements:", integer_elements)

# ii
float_elements = array[array % 1 != 0]
print("Float elements:", float_elements)


Sorted array: [ 10  16  16  52  54  62 453]
Indices of sorted array: [0 3 4 1 5 2 6]
4 smallest elements: [10 16 16 52]
5 largest elements: [ 16  52  54  62 453]
Integer elements: [1. 2. 3. 2.]
Float elements: [1.2 2.2]

# question 4

# Q4)

# a)
from PIL import Image
import numpy as np

def img_to_array(path):
    try:
        img = Image.open(path)
        img_array = np.array(img)

        if img.mode == 'RGB':
            np.savetxt('image_rgb.txt', img_array.reshape(-1, 3), fmt='%d')
            print("RGB image array saved as 'image_rgb.txt'")
        elif img.mode == 'L':
            np.savetxt('image_grey.txt', img_array, fmt='%d')
            print("Grayscale image array saved as 'image_grey.txt'")
        else:
            print("Unsupported image mode:", img.mode)
    except Exception as e:
        print("Error:", e)

# Example usage
img_to_array('/content/image_rgb.png')


# b)



# # Assuming the image was saved as image_rgb.txt or image_grey.txt
# img_array_loaded_rgb = np.loadtxt('image_rgb.txt').reshape(-1, 3)
# img_array_loaded_grey = np.loadtxt('image_grey.txt')
# print("Loaded RGB image array:", img_array_loaded_rgb)
# print("Loaded Grey Scale image array:", img_array_loaded_grey)



